"""Public package interface for the spectral packet engine."""

from spectral_packet_engine.basis import InfiniteWellBasis, eigenenergy, eigenenergies, sine_basis_matrix
from spectral_packet_engine.datasets import (
    DensityPreprocessingConfig,
    PreparedDensityProfiles,
    PreparedShotDensityProfiles,
    QuantumGasTransportScan,
    available_quantum_gas_transport_scans,
    download_and_prepare_quantum_gas_transport_shots,
    download_and_prepare_quantum_gas_transport_scan,
    fetch_quantum_gas_transport_scan,
    load_quantum_gas_transport_scan,
)
from spectral_packet_engine.domain import InfiniteWell1D, InfiniteWellDomain
from spectral_packet_engine.dynamics import SpectralPropagator, phase_factors
from spectral_packet_engine.inference import (
    EstimationConfig,
    GaussianPacketEstimator,
    ObservationMode,
    ReconstructionResult,
)
from spectral_packet_engine.observables import (
    expectation_position,
    grid_probability_density,
    interval_probability,
    l2_norm,
    total_probability,
    variance_position,
)
from spectral_packet_engine.profiles import (
    ProfileCompressionResult,
    ProfileCompressionSummary,
    compress_profiles,
    modal_energy,
    modal_tail,
    normalize_profiles,
    profile_mass,
    profile_mean,
    profile_variance,
    project_profiles_onto_basis,
    reconstruct_profiles_from_basis,
    relative_l2_error,
    summarize_profile_compression,
)
from spectral_packet_engine.projector import ProjectionConfig, StateProjector
from spectral_packet_engine.runtime import TorchRuntime, inspect_torch_runtime, resolve_torch_device
from spectral_packet_engine.simulation import SimulationRecord, simulate
from spectral_packet_engine.state import (
    GaussianPacketParameters,
    PacketState,
    SpectralState,
    make_truncated_gaussian_packet,
)
from spectral_packet_engine.tf_surrogate import (
    TensorFlowHostPlatform,
    TensorFlowModalRegressionResult,
    TensorFlowModalRegressor,
    TensorFlowRegressorConfig,
    TensorFlowRuntime,
    configure_tensorflow_runtime,
    inspect_tensorflow_host,
    tensorflow_is_available,
)

__all__ = [
    "DensityPreprocessingConfig",
    "EstimationConfig",
    "GaussianPacketEstimator",
    "GaussianPacketParameters",
    "InfiniteWell1D",
    "InfiniteWellBasis",
    "InfiniteWellDomain",
    "ObservationMode",
    "PacketState",
    "PreparedDensityProfiles",
    "PreparedShotDensityProfiles",
    "ProfileCompressionResult",
    "ProfileCompressionSummary",
    "ProjectionConfig",
    "QuantumGasTransportScan",
    "ReconstructionResult",
    "SimulationRecord",
    "SpectralPropagator",
    "SpectralState",
    "StateProjector",
    "TensorFlowModalRegressionResult",
    "TensorFlowModalRegressor",
    "TensorFlowRegressorConfig",
    "TensorFlowRuntime",
    "TensorFlowHostPlatform",
    "available_quantum_gas_transport_scans",
    "compress_profiles",
    "configure_tensorflow_runtime",
    "download_and_prepare_quantum_gas_transport_shots",
    "download_and_prepare_quantum_gas_transport_scan",
    "eigenenergy",
    "eigenenergies",
    "expectation_position",
    "fetch_quantum_gas_transport_scan",
    "grid_probability_density",
    "interval_probability",
    "inspect_tensorflow_host",
    "inspect_torch_runtime",
    "l2_norm",
    "load_quantum_gas_transport_scan",
    "make_truncated_gaussian_packet",
    "modal_energy",
    "modal_tail",
    "normalize_profiles",
    "phase_factors",
    "profile_mass",
    "profile_mean",
    "profile_variance",
    "project_profiles_onto_basis",
    "reconstruct_profiles_from_basis",
    "relative_l2_error",
    "resolve_torch_device",
    "simulate",
    "sine_basis_matrix",
    "summarize_profile_compression",
    "tensorflow_is_available",
    "total_probability",
    "TorchRuntime",
    "variance_position",
]
