from __future__ import annotations

"""Core bounded-domain spectral engine surface."""

from spectral_packet_engine.basis import InfiniteWellBasis, eigenenergy, eigenenergies, sine_basis_matrix
from spectral_packet_engine.diagnostics import (
    ProfileComparisonSummary,
    ReconstructionErrorSummary,
    SpectralBatchSummary,
    SpectralTruncationSummary,
    mode_counts_for_mass,
    spectral_tail_mass,
    spectral_weights,
    summarize_profile_comparison,
    summarize_profile_reconstruction,
    summarize_spectral_batch,
    summarize_spectral_coefficients,
)
from spectral_packet_engine.domain import InfiniteWell1D, InfiniteWellDomain
from spectral_packet_engine.dynamics import SpectralPropagator, phase_factors
from spectral_packet_engine.inference import (
    EstimationConfig,
    GaussianPacketEstimator,
    ObservationMode,
    ReconstructionResult,
)
from spectral_packet_engine.observables import (
    expectation_position,
    grid_probability_density,
    interval_probability,
    l2_norm,
    total_probability,
    variance_position,
)
from spectral_packet_engine.profiles import (
    ProfileCompressionResult,
    ProfileCompressionSummary,
    compress_profiles,
    modal_energy,
    modal_tail,
    normalize_profiles,
    profile_mass,
    profile_mean,
    profile_variance,
    project_profiles_onto_basis,
    reconstruct_profiles_from_basis,
    relative_l2_error,
    summarize_profile_compression,
)
from spectral_packet_engine.projector import ProjectionConfig, StateProjector
from spectral_packet_engine.runtime import TorchRuntime, inspect_torch_runtime, resolve_torch_device
from spectral_packet_engine.simulation import SimulationRecord, simulate
from spectral_packet_engine.state import (
    GaussianPacketParameters,
    PacketState,
    SpectralState,
    make_truncated_gaussian_packet,
)
from spectral_packet_engine.workflows import (
    EngineContext,
    ForwardSimulationSummary,
    InverseFitSummary,
    PacketProjectionSummary,
    PacketSweepItemSummary,
    PacketSweepSummary,
    ProfileCompressionSweepSummary,
    ProfileCompressionWorkflowResult,
    ProfileTableComparisonWorkflowResult,
    ProfileTableSpectralSummary,
    ProfileTableSummary,
    build_engine,
    compare_profile_tables,
    compress_profile_table,
    fit_gaussian_packet_to_density,
    fit_gaussian_packet_to_profile_table,
    make_packet_state,
    project_gaussian_packet,
    simulate_gaussian_packet,
    simulate_packet_sweep,
    summarize_profile_table,
    sweep_profile_table_compression,
)

__all__ = [
    "EngineContext",
    "EstimationConfig",
    "ForwardSimulationSummary",
    "GaussianPacketEstimator",
    "GaussianPacketParameters",
    "InfiniteWell1D",
    "InfiniteWellBasis",
    "InfiniteWellDomain",
    "InverseFitSummary",
    "ObservationMode",
    "PacketProjectionSummary",
    "PacketSweepItemSummary",
    "PacketSweepSummary",
    "PacketState",
    "ProfileComparisonSummary",
    "ProfileTableComparisonWorkflowResult",
    "ProfileCompressionResult",
    "ProfileCompressionSummary",
    "ProfileCompressionSweepSummary",
    "ProfileCompressionWorkflowResult",
    "ProfileTableSpectralSummary",
    "ProfileTableSummary",
    "ProjectionConfig",
    "ReconstructionErrorSummary",
    "ReconstructionResult",
    "SimulationRecord",
    "SpectralBatchSummary",
    "SpectralPropagator",
    "SpectralState",
    "SpectralTruncationSummary",
    "StateProjector",
    "TorchRuntime",
    "build_engine",
    "compare_profile_tables",
    "compress_profile_table",
    "compress_profiles",
    "eigenenergy",
    "eigenenergies",
    "expectation_position",
    "fit_gaussian_packet_to_density",
    "fit_gaussian_packet_to_profile_table",
    "grid_probability_density",
    "inspect_torch_runtime",
    "interval_probability",
    "l2_norm",
    "make_packet_state",
    "make_truncated_gaussian_packet",
    "modal_energy",
    "modal_tail",
    "mode_counts_for_mass",
    "normalize_profiles",
    "phase_factors",
    "profile_mass",
    "profile_mean",
    "profile_variance",
    "project_gaussian_packet",
    "project_profiles_onto_basis",
    "reconstruct_profiles_from_basis",
    "relative_l2_error",
    "resolve_torch_device",
    "simulate",
    "simulate_gaussian_packet",
    "simulate_packet_sweep",
    "sine_basis_matrix",
    "spectral_tail_mass",
    "spectral_weights",
    "summarize_profile_comparison",
    "summarize_profile_compression",
    "summarize_profile_reconstruction",
    "summarize_profile_table",
    "summarize_spectral_batch",
    "summarize_spectral_coefficients",
    "sweep_profile_table_compression",
    "total_probability",
    "variance_position",
]
