from __future__ import annotations

"""Backend-aware modal surrogate surface around the spectral engine."""

from spectral_packet_engine.ml import (
    JAXModalRegressor,
    MLBackendReport,
    MLBackendRuntime,
    ModalBackendResolution,
    ModalRegressionResult,
    ModalSurrogateConfig,
    PyTorchModalRegressor,
    TensorFlowModalRegressorAdapter,
    create_modal_regressor,
    inspect_jax_backend,
    inspect_ml_backends,
    inspect_tensorflow_backend,
    inspect_torch_backend,
    jax_is_available,
    resolve_modal_backend,
)
from spectral_packet_engine.tf_surrogate import (
    TensorFlowHostPlatform,
    TensorFlowModalRegressionResult,
    TensorFlowModalRegressor,
    TensorFlowRegressorConfig,
    TensorFlowRuntime,
    configure_tensorflow_runtime,
    inspect_tensorflow_host,
    tensorflow_is_available,
)
from spectral_packet_engine.workflows import (
    ModalEvaluationSummary,
    ModalTrainingSummary,
    TensorFlowEvaluationSummary,
    TensorFlowTrainingSummary,
    evaluate_modal_surrogate_from_database_query,
    evaluate_modal_surrogate_on_profile_table,
    evaluate_tensorflow_surrogate_on_profile_table,
    inspect_ml_backend_support,
    train_modal_surrogate_from_database_query,
    train_modal_surrogate_on_profile_table,
    train_tensorflow_surrogate_on_profile_table,
)

__all__ = [
    "JAXModalRegressor",
    "MLBackendReport",
    "MLBackendRuntime",
    "ModalBackendResolution",
    "ModalEvaluationSummary",
    "ModalRegressionResult",
    "ModalSurrogateConfig",
    "ModalTrainingSummary",
    "PyTorchModalRegressor",
    "TensorFlowEvaluationSummary",
    "TensorFlowHostPlatform",
    "TensorFlowModalRegressionResult",
    "TensorFlowModalRegressor",
    "TensorFlowModalRegressorAdapter",
    "TensorFlowRegressorConfig",
    "TensorFlowRuntime",
    "TensorFlowTrainingSummary",
    "configure_tensorflow_runtime",
    "create_modal_regressor",
    "evaluate_modal_surrogate_from_database_query",
    "evaluate_modal_surrogate_on_profile_table",
    "evaluate_tensorflow_surrogate_on_profile_table",
    "inspect_jax_backend",
    "inspect_ml_backends",
    "inspect_ml_backend_support",
    "inspect_tensorflow_backend",
    "inspect_tensorflow_host",
    "inspect_torch_backend",
    "jax_is_available",
    "resolve_modal_backend",
    "tensorflow_is_available",
    "train_modal_surrogate_from_database_query",
    "train_modal_surrogate_on_profile_table",
    "train_tensorflow_surrogate_on_profile_table",
]
